name: Site Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        users: actions/checkout@v3
      
      - name: Install dependencies
        run: npm ci
        env:
          NODE_ENV: production
      
      - name: Build
        run: npm run build
      
      - name: Deploy
        run: |
          rsync -avz --delete ./public/ {{ secrets.DEPLOY_ADDRESS }}:/var/www/chris.budy.org/odh/